# Generated by Django 5.2.14 on 2026-05-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='events_event',
        ),
    ]
