# Generated by Django 5.2.14 on 2026-05-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_alter_issue_status'),
        ('users', '0004_registrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='users.juristicofficer'),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('noise', 'Noise'), ('cleanliness', 'Cleanliness'), ('safety', 'Safety'), ('parking', 'Parking'), ('neighbor', 'Neighbor'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reported_issues', to='users.resident'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterModelTable(
            name='complaint',
            table='issues_complaint',
        ),
        migrations.AlterModelTable(
            name='issue',
            table='issues_issue',
        ),
        migrations.AlterModelTable(
            name='maintenance',
            table='issues_maintenance',
        ),
    ]
