# Generated by Django 5.2.14 on 2026-05-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_remove_house_owner_house_created_at_house_updated_at_and_more'),
        ('users', '0005_remove_technician_skill_set_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('visitor_name', models.CharField(max_length=100)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('schedule_date', models.DateTimeField()),
                ('qr_code_string', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_visitor_passes', to='users.resident')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_passes', to='properties.house')),
            ],
            options={
                'db_table': 'visitors_visitorpass',
            },
        ),
    ]
