# Generated by Django 5.2.14 on 2026-05-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_assigned_officer_issue_updated_at_and_more'),
        ('skills', '0001_initial'),
        ('users', '0004_registrationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='skill_set',
        ),
        migrations.AddField(
            model_name='technician',
            name='current_maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_technician_slots', to='issues.maintenance'),
        ),
        migrations.AddField(
            model_name='technician',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='technicians', through='skills.TechnicianSkill', to='skills.skill'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='permission_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('super', 'Super')], default='basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='technician',
            name='current_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('off_duty', 'Off duty')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('resident', 'Resident'), ('technician', 'Technician'), ('juristic_officer', 'Juristic Officer'), ('security', 'Security')], default='resident', max_length=20),
        ),
    ]
