# Generated by Django 5.2.14 on 2026-05-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'regulations_regulation',
            },
        ),
    ]
